repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-report_logo_light.png
    - docs/images/nf-core-report_logo_light.png
    - docs/images/nf-core-report_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config: false
  multiqc_config:
    - report_comment
  schema_params: false
  files_exist:
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-report_logo_light.png
    - docs/images/nf-core-report_logo_light.png
    - docs/images/nf-core-report_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - tests/default.nf.test
template:
  org: nf-cmgg
  name: report
  description: A post-processing reporting pipeline for internal use at CMGG
  author: Tuur-ds,nvnieuwk
  version: 1.0.0
  force: true
  outdir: ./report
  skip_features:
    - multiqc
    - fastqc
    - igenomes
  is_nfcore: false
